var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function (req, res) {
	res.render('objectives');
});

router.post('/save', function (req, res) {
	console.log(req.body.objectives);	
	res.send({ "score": "half wit consultant" });
});

router.get('/list', function (req, res) {
	var list =
	{
		data:
		[
			{
				"reviewedObjective": "Organizes work and manage teams to achieve specific goals or outcomes",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Be assigned on a project in a leadership capacity where your responsibilities include creating and assigning tasks to other team members.",
				"counterExample": "Non-lead role on team; independent work; defining work but not actively managing others",
				"Notes": "",
				"Number": 3
			},
			{
				"reviewedObjective": "Actively participates in initiatives that improve Online,  in the development of plans for new business processes, change management, internal projects or programs",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Involved in the planning and execution of internal projects or initiatives, Business Planning, Practice Planning, Career Mentor Program",
				"counterExample": "Normal project work, personal development projects, involvement in clubs or communities of interest",
				"Notes": "",
				"Number": 4
			},
			{
				"reviewedObjective": "Adapts verbal communication (e.g. message, style, level of detail, etc.) based on audience dynamics and feedback",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "During the course of a presentation be able to identify when your audience isn't understanding your message and modify so that they do. Successfully adapted the messaging of a client presentation on-the-fly that was not being well received. ",
				"counterExample": "Creating a document (Word, email or PPT) for different people (the key is \"dynamically\").",
				"Notes": "How can anybody demonstrate / prove this?",
				"Number": 5
			},
			{
				"reviewedObjective": "Assumes a leadership role in the creation of proposal submissions and solution definition",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Has been assigned to or taken responsibility for solution definition, bid management, bid authoring or pricing",
				"counterExample": "Has elaborated solution details, authored or edited content, provided administrative support for bids",
				"Notes": "",
				"Number": 6
			},
			{
				"reviewedObjective": "Has fulfilled a leadership role in external user groups / professional organizations",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Filled a board role; chaired a committee; played an organizational advisory role",
				"counterExample": "Participant in an organization or committee (even if a key contributor)",
				"Notes": "",
				"Number": 7
			},
			{
				"reviewedObjective": "Assures the practical needs of a team are met (e.g. hardware / tools / SME access / etc.)",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is the person responsible for ensuring the team has the tools necessary to do their job. This could be from working with Infrastructure Services to get accounts and groups setup to talking to Corporate Executive Assistance to get keys and access for members of the team.",
				"counterExample": "Advocate for unmet needs, even if loudly enough that needs were addressed. (i.e. Getting a mouse for a co-worker from Infrastructure Services - the key is that while helpful you are not identified as the person responsible for satisfying any non domain specific issues for the team)",
				"Notes": "",
				"Number": 8
			},
			{
				"reviewedObjective": "Creates formulas, styles, tables, references, page layouts, etc. using Microsoft Word and Excel, or other industry standard tools (e.g. OpenOffice, GoogleDocs, etc.)",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 1,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Designing templates for standard documents with consistent style across deliverables contributed to by multiple people; leveraging more advanced features to produce high quality, professional looking artifacts in Word, e.g. sets of styles linked to outline, consistent tables, customized tables of contents, labeled cross references, sectioned headers and footers in documents with page numbering and logos; leveraging more advanced capabilities in Excel to create solutions that might otherwise require programming, e.g. data filtering, icons, conditional formatting, custom formatting for printing, drop downs, labels, complex formulae with lookups, macros, VBA, charts, pivot tables, etc.",
				"counterExample": "Comfort using office tools to create simple, effective documents, spreadsheets, etc.; ability to work with preconfigured styles, e.g. Online Resume or Proposal templates",
				"Notes": "",
				"Number": 10
			},
			{
				"reviewedObjective": "Creates styles, tables, animations, references, page layouts, etc. using PowerPoint or other industry standard tools (e.g. Prezi, Keynote)",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 1,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Creating templates for standard presentations with consistent style across deliverables contributed to by multiple people or that need to be consistent over time (e.g. dashboards); leveraging more advanced features to produce high impact, professional presentations, e.g. embedded multimedia, transitions, animations / build slides, changing master slides, embedded images from other tools that look good (e.g. Visio models), etc.",
				"counterExample": "Comfort using presentation tools to create simple, effective presentations; ability to work with preconfigured styles, e.g. Online Presentation templates",
				"Notes": "",
				"Number": 11
			},
			{
				"reviewedObjective": "Effectively determines the appropriate audience with which to communicate (i.e. targets the right individual, group or organizational level)",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Understands the dynamics within the client organization and finds the right person from which to solicit information. Actively including / excluding individuals, bypassing expected channels, choosing between business and technical audiences, conscious stakeholder analysis in communication planning.",
				"counterExample": "Tailoring messages or language for specific audiences, communicating with senior individuals",
				"Notes": "This one feels more nebulas as well, what is a counter example - only talking to one person?",
				"Number": 12
			},
			{
				"reviewedObjective": "Clearly communicates expectations to the team and tracks performance against expectations",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Team lead that explicitly communicates expectations and addresses deviation. Responsible for explaining the big-picture objectives to the team as well as monitoring the task break-down.",
				"counterExample": "Talks to peers about outstanding work and/or writes status reports. Team lead  works around problem team members or issues.",
				"Notes": "",
				"Number": 13
			},
			{
				"reviewedObjective": "Communicates effectively with both technical and non technical resources",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 1,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is able to speak in terms that either a technical or non-technical resource can understand. This could include using more every-day type of scenario when attempting to describe a technical process to a less-technical individual (e.g. BA or Sales) or describing the process which is responsible for implementing a requirement when talking to a more technical resource (e.g. developer).",
				"counterExample": "Only comfortable with one or the other. Talking slower, reiterating the same thing.",
				"Notes": "Who wouldn't say they can do this? And if they so \"no\" is that because they're in a non-tech role (BA/PM) and if so - are they being penalized?",
				"Number": 14
			},
			{
				"reviewedObjective": "Contributes to the creation of internal IP (e.g.. Deliverables, methodologies) and/or initiatives / groups (e.g. book club)",
				"Communication": "",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Works with a group of other Onliners to define or create internal IP. Helping to develop a corporate initiative (i.e. Feedback), developing a methodology (i.e. App Dev Methods), or working with a Practice Lead to further the goals of the practice. ",
				"counterExample": "Participating in company events such as Corporate BBQs, Tech Services Events, Study Groups, or delivering Lunch & Learns. Managing multiple priorities/workloads in themselves doesn't qualify- you have to meet deadlines or receive acknowledgement that delays are acceptable.",
				"Notes": "",
				"Number": 15
			},
			{
				"reviewedObjective": "Deals effectively with changing priorities, workloads and/or multiple client projects with a positive outcome",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is responsible for multiple deliverables within a single time-frame and consistently delivers successfully. Example: working on multiple client engagements/assignments concurrently, or having RFP / internal IP / initiative responsibilities while assigned to a project.",
				"counterExample": "Having multiple deliverables on your current project or dealing with clients that change their mind mid-way through the project.",
				"Notes": "Wondering if we should can \"changing priorities\"?",
				"Number": 16
			},
			{
				"reviewedObjective": "Delivers effective presentations and/or speaks at internal community events ",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Prepared and delivered good presentations at Online staff meetings, lunch and learns, or other internal training that receives positive feedback from the audience (either immediately or later through discussion or email).",
				"counterExample": "Speaking up or asking questions at staff meetings, supporting role in presentations, delivering an ad-hoc presentation, or speaking at Toastmasters  with (or without) little-to-none positive feedback.",
				"Notes": "Do we need to say that Toastmasters does NOT count here?",
				"Number": 17
			},
			{
				"reviewedObjective": "Delivers effective presentations at community or industry events (e.g. conferences, speaking engagements)",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Delivers an external presentation that receives positive feedback from the audience (either immediately or later through discussion or email).",
				"counterExample": "Participates in a discussion with the speaker during a meeting / presentation. Any speaking presentation which would qualify for objective (17)",
				"Notes": "",
				"Number": 18
			},
			{
				"reviewedObjective": "Demonstrates good judgment in selecting appropriate modes of communication",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Understands when to give up on the email exchange and get up and walk over to (or call) the person you're communicating with. Ultimately - understands when email won't cut it anymore, and when email is required to ensure traceability. Chooses between spoken and written communication based on message, potential impact, formality, non-repudiation",
				"counterExample": "Ability to communicate effectively across different mediums. Using texts, or unprofessional methods of communication, to tell a client what is going wrong at the client site. ",
				"Notes": "What's a counter example that could possible exclude someone?",
				"Number": 19
			},
			{
				"reviewedObjective": "Demonstrates how to take a complex thought/idea and convey it in a clear and concise manner to any audience",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Prepares effective solutions / proposals or contrasts subtle differences between alternatives from different viewpoints. This may be creating a PPT with examples / pictures or knowing the right scenarios to use.",
				"counterExample": "Having an expectation that audience members to bring enough context with them.. Exclude when displaying a bunch of detailed charts, numbers, or graphs, and then not explaining what the relevance of the numbers are. Presentations typically do not remained confined to the meeting in which they were originally scheduled to be delivered. The key to effectively delivering content is knowing what to include and (more importantly) exclude.",
				"Notes": "Again, another question that I think everyone will get - what is a counter example?",
				"Number": 20
			},
			{
				"reviewedObjective": "Encourages and facilitates cooperation, open communication and transparency within a team",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Ensures that members of the team are aware of issues as well as accolades. Ensuring communication channels are outlined to everyone up front. If in a leadership position, ensuring that the team is aware of how their work is affecting the client and ensuring they are apprised of what is happening within the project from a client / leadership perspective. Actively seeks to plan for and assure inclusive communication on a project; breaks down unnecessary barriers",
				"counterExample": "Providing status updates. \"Protecting\" the team from issues (the issue can be shared with an explicit understanding that it is informational and that there is no expectation that the team will act on the information). Communicating issues, progress, and praise solely to project executives, stakeholders, and BD without including the team.\n",
				"Notes": "Is this different than #9?",
				"Number": 21
			},
			{
				"reviewedObjective": "Expected to lead communication with client, system users, and have direct communication on a regular basis with IT or business managers in either group or one-on-one situations",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "In a leadership position and is the person the client turns to when they are looking for information (regardless if it's senior business or technical resource). Assumed roles with responsibility for key lines of communication with client participants / stakeholders.",
				"counterExample": "Talking with the client resources / SMEs. Effective client, business or end user communication and interactions. Getting approval from more senior Onliners prior to engaging in discussions with clients.",
				"Notes": "",
				"Number": 22
			},
			{
				"reviewedObjective": "Holds team members accountable for their responsibilities and takes corrective action when necessary",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "In a leadership position is responsible for following up on assigned deliverables; if those deliverables don't meet expectations or deadlines, working with the resource to develop a strategy to improve and/or change. If, after time, it is clear the resource is incapable of working to expectation then you need to work with project leadership (and / or CMs) to have the resource removed. Has taken progressive steps to correct behavior on a team; escalating concerns over weak contributors that are impacting the team.",
				"counterExample": "Identifying incomplete deliverables and then reassigning work (or taking it on yourself) to ensure client's expectations / deadlines are met.",
				"Notes": "",
				"Number": 23
			},
			{
				"reviewedObjective": "Identifies Onliners who appear to be having personal problems and takes appropriate steps to discuss and/or escalate",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Proactively intervening when someone seems to be having trouble coping emotionally; sharing concerns about the well-being of others with regional leadership or PeopleCare. Onliners with enough experience to know how to help other Onliners by offering to provide advice or directing them to the appropriate resource.",
				"counterExample": "Being aware of issues and working around them, but avoiding getting involved. Noticing that someone is having personal issues and telling them to \"cheer up\" or \"things will get better\". Assisting Onliners with personal issues that have been openly discussed with the team / openly acknowledged.",
				"Notes": "",
				"Number": 24
			},
			{
				"reviewedObjective": "Identifies required skill sets and selects individuals to accomplish specific tasks",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 2,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Having the experience to understand how to solve a specific problem and know the abilities of the resources on the project enough to understand who would be capable of working on the task",
				"counterExample": "Volunteering a technology, pattern or framework for a technical problem.",
				"Notes": "",
				"Number": 25
			},
			{
				"reviewedObjective": "Identifies when support is required to achieve goals and asks  for support",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Onliner proactively asks for help/support before projects, initiatives, deliverables, get off track.",
				"counterExample": "Waiting until a project, initiative, deliverable is off track before you seek help or support.",
				"Notes": "",
				"Number": 26
			},
			{
				"reviewedObjective": "Delivers high level cost or time estimates for planning purposes",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Onliner is identified by the client or senior Online resources as someone who has proven their ability to estimate their own time accurately as well as deliver or assist in the creation of estimates for individuals or teams.",
				"counterExample": "Provides input or feedback on estimates created by other resources. Providing estimates on remaining work for your current task. ",
				"Notes": "",
				"Number": 27
			},
			{
				"reviewedObjective": "Is competent in UML or other industry standards modeling / diagramming techniques that Online uses in project delivery",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Understands the different types of diagrams and where they are applicable (e.g. Class, Sequence, Timing, Use Case) and is able to use them to help elicit or clarify requirements",
				"counterExample": "Only familiar with one type of diagram or know multiple diagrams but never responsible for creating them.",
				"Notes": "",
				"Number": 29
			},
			{
				"reviewedObjective": "Is effective at self-managing conflict, issues, and stress ",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Doesn't get (noticeably) upset / flustered (including backing down / becoming quiet) when placed in a situation with conflict. Conversely does not become overly aggressive. Is capable of maintaining composure and still meet / manage expectations during high stress situations (e.g. tight deadlines).",
				"counterExample": "Communicating with others about the conflict to reduce your own stress levels but not dealing with it head on with the person who is directly involved.",
				"Notes": "What's a counter example of this?",
				"Number": 30
			},
			{
				"reviewedObjective": "Is persuasive in influencing the decisions, opinions, attitudes and behaviors of the Client",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Typically in a leadership role, is responsible for presenting solutions to the client which entail describing how some requirements will be met (which may differ than original expectations). Can demonstrate having presented a client with multiple options or alternatives and had the client's opinion change to match the presented options.\n",
				"counterExample": "Discussing implementation details with a SME. Adamantly insisting your ideas are correct and the client must take your advice or the project will suffer.",
				"Notes": "Feel like we should stress LEADERSHIP",
				"Number": 31
			},
			{
				"reviewedObjective": "Is persuasive in influencing the decisions, opinions, attitudes and behaviors of Onliners",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Typically in a leadership role, has demonstrated the ability to get Onliners \"on-board\" with a new or unfamiliar idea or process. ",
				"counterExample": "Contributing to the creation of IP which is adopted by the organization.",
				"Notes": "",
				"Number": 32
			},
			{
				"reviewedObjective": "Is recognized as a mentor to others in crafting both verbal and/or written communications",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 4,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is routinely (i.e. more than twice) sought out by Onliners or clients to provide input to their emails, documents, how they should approach a difficult conversation/meeting, or how to planning a senior stakeholder presentation.",
				"counterExample": "Proof reading emails or documents for your team mates",
				"Notes": "",
				"Number": 33
			},
			{
				"reviewedObjective": "Is requested by Onliners to help them work through client and /or internal issues ",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 5,
				"Score": 2,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is routinely (i.e. more than twice) sought out by other Onliners to help with issues either on their project or within Online. Often this is someone in a CM or project leadership role",
				"counterExample": "Providing someone with a SharePoint link or contact information for another senior Onliner.",
				"Notes": "Think we need to stress the leadership / cm thing here (we scored it a 2)",
				"Number": 34
			},
			{
				"reviewedObjective": "Is responsible for and effective at delivering presentations at an executive level",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Onliner is the individual responsible for pulling the content together and leading the delivery of the materials to executive that receives positive feedback from the audience (either immediately or later through discussion or email).",
				"counterExample": "Participating in the group that developed the material and / or helped deliver the presentation.",
				"Notes": "Guess we need something for \"effective\" here",
				"Number": 35
			},
			{
				"reviewedObjective": "Is responsible for delivering presentations at internal community, or project leadership levels",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "<self-explanatory>",
				"counterExample": "<self-explanatory>",
				"Notes": "",
				"Number": 36
			},
			{
				"reviewedObjective": "Is responsible for managing the relationship at all levels within the client, including key senior stakeholders",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Onliner is the individual that the client turns to when there are project issues or concerns. A trusted resource: e.g. The client will ask you to interview resources on their behalf.",
				"counterExample": "Has a \"good\" relationship with the client but ultimately does not impact billable decisions or extensions. Hasn't identified new opportunities for either themselves or other Onliners (resulting in more Onliners getting engaged). Onliners in a staff augmentation role as the only resource would not necessarily meet the Objective.",
				"Notes": "okay - getting tired, the counter ex feels weak",
				"Number": 37
			},
			{
				"reviewedObjective": "Is solicited by BD to work on proposals, presentations and other BD related assignments",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "BD specifically asks you to develop content for them, or speak to a client based on your experience and seniority across multiple roles vs. specifically requesting details about your current or previous role.",
				"counterExample": "Updating your resume with a summary of a project you were on ",
				"Notes": "",
				"Number": 38
			},
			{
				"reviewedObjective": "Is sought out by BD / other consultants to review or correct project proposals / technical documentation / RFPs / architecture documentation / etc.",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "<self-explanatory>",
				"counterExample": "<self-explanatory>",
				"Notes": "This feels like a duplicate of 6 and 33",
				"Number": 39
			},
			{
				"reviewedObjective": "Is trusted to communicate independently on behalf of Online, both written and verbal.",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Setting up meetings with external organization, setting up events, participating with BD on sales calls, being the single Onliner on a client-site project",
				"counterExample": "Has one-on-one meetings with  client resources",
				"Notes": "",
				"Number": 40
			},
			{
				"reviewedObjective": "Leads and facilitates meetings effectively, including agenda and duration",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "In a role where you are responsible for planning, scheduling and facilitating a meeting with three or more people. Responsible for ensuring all people are heard and the meeting stays focused. Typically responsible for sending out meeting minutes and following up on any Action Items identified.",
				"counterExample": "Sitting down with a small group and discussing aspects of the project",
				"Notes": "",
				"Number": 41
			},
			{
				"reviewedObjective": "Makes a team feel ownership for a project and / or problem to encourage individual investment",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Shares details about the project, looks to the team for input and suggestions. Empower people to make decisions (and mistakes). Delegates responsibilities to project team members and encourages them to investigate solutions and provide options.",
				"counterExample": "Assign tasks without sharing big picture. \"Protect\" team from issues with the client by not sharing what is happening.",
				"Notes": "how is this different from 9 & 21?",
				"Number": 43
			},
			{
				"reviewedObjective": "Mediates pro-actively between individuals to resolve interpersonal conflicts",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 3,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Is trusted by all parties to diffuse a situation. Is seen as the \"voice of reason\" and can find a compromise for all parities. Typically requires someone with some influence being in a leadership position",
				"counterExample": "Resolves disagreements, disputes, or low-level questions related to technical approaches for project deliverables. Assists with identifying the best course of action when implementing technical solutions or proof reading documentation.",
				"Notes": "",
				"Number": 44
			},
			{
				"reviewedObjective": "Participates in external user groups / professional organizations",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 1,
				"Gate Level (I / S)": "I",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Participates at least quarterly in external user groups / professional organization events a year.",
				"counterExample": "Attends a user group meeting once.",
				"Notes": "",
				"Number": 45
			},
			{
				"reviewedObjective": "Proactively anticipates issues and risks and develops approaches to avoid, mitigate or prepare for them",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Leadership  Management effort: Documenting options.. Gathering information from the team and balancing against feedback from the client. Employing strategies to identify risks early and often. Provide a comprehensive list of options and suggest the next course of action including pros, cons and reason for selection. Engages senior project resources to vet suggestions put forward by the team. Dealing with Project Level issues (Macro vs. Micro)",
				"counterExample": "Communicate issues early and often but missing remediation suggestions. Identifying issues within the task you are assigned and finding work-arounds",
				"Notes": "",
				"Number": 50
			},
			{
				"reviewedObjective": "Provides effective feedback as a way to help others develop",
				"Communication": "Yes",
				"Leadership \nManagement": "",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 2,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Feedback contains constructive feedback consisting of specific examples and suggestions for improvement or growth. Follows Online's documented Feedback method.",
				"counterExample": "Feedback consists of just praise or the \"area of growth\" consists of a suggestion with no reason (e.g. Learn more Java).",
				"Notes": "",
				"Number": 51
			},
			{
				"reviewedObjective": "Recognized as a mentor and leader by senior client team members, and external consultants",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 3,
				"Gate Level (I / S)": "S",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Looked to provide guidance to the organization or project. Looked to by the client to take leadership roles within the project. Expected to mentor others (including Onliners and clients).",
				"counterExample": "Being really smart",
				"Notes": "",
				"Number": 52
			},
			{
				"reviewedObjective": "Recognizes potential in individuals and facilitates opportunities for their growth and recognition",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Recognizing that a developer has an affinity for managing people and tasks, advises that person's CM of the potential for project lead or project management career growth, and follows through with CM, business development, etc. to support that Onliner.",
				"counterExample": "Providing encouragement or feedback during or after an Onliner's engagement with a client.",
				"Notes": "",
				"Number": 54
			},
			{
				"reviewedObjective": "Represents and promotes a groups reputation with Online Management and/or the Client",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 2,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Proactively ensuring your team members strengths, accomplishments and commitments are made known to the client and or OBS Management Team. It is giving people the recognition they deserve for the work they have done.",
				"counterExample": "Acknowledging the work of others and abstaining from showcasing efforts of the team and / or specific team members",
				"Notes": "Remove \"protects\" as that is covered in 60 Replaced \"other\" to be Management & Client",
				"Number": 55
			},
			{
				"reviewedObjective": "Rewards effort, hard work and results; actively promotes high performers and eliminates non-contributors",
				"Communication": "Yes",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "Yes",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 4,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Ensures that hard work is noticed, acknowledged and rewarded. It is ensuring that those who are not meeting expectations are aware they are not meeting expectations and that required steps are taken to address this if performance/behavior does not change.",
				"counterExample": "Accepting high performers picking up the slack for poor performers . It isnt treating high and low performers the same and not acknowledging the difference between both.",
				"Notes": "",
				"Number": 56
			},
			{
				"reviewedObjective": "Supports the recruiting process by assisting in identifying, attracting, evaluating and recommending qualified people to Online",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "Yes",
				"Competency Weighting": 3,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Participate in recruiting by interviewing or helping at a recruiting event (e.g. at a job faire). Provides detailed evaluations to People care in a timely manner.",
				"counterExample": "Forwards a resume for a potential hire to People care. Provides a go/no go call for a candidate with no supporting details",
				"Notes": "Need something about evaluation here (i.e. explaining WHY we should, or should NOT hire someone)",
				"Number": 59
			},
			{
				"reviewedObjective": "Takes responsibility for outcomes produced by team and takes steps to address shortcomings",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 1,
				"Score": 1,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Ensures that expectations have been managed so that any outcome is fully anticipated and not a surprise. Proactively focuses on developing alternatives to issues / risks. Takes responsibility for deliverables",
				"counterExample": "Explains the problem with the project was due to things like \"new resources\", \"incomplete requirements\", \"server issues\", \"technology deficiencies\" . Makes excuses for deliverables",
				"Notes": "",
				"Number": 60
			},
			{
				"reviewedObjective": "Undertakes, and follows through on additional responsibilities willingly",
				"Communication": "",
				"Leadership \nManagement": "Yes",
				"Interpersonal\nAdaptability": "Yes",
				"Conflict-Stress\nManagement": "",
				"Corporate\nCitizenship": "",
				"Competency Weighting": 2,
				"Score": 2,
				"Gate Level (I / S)": "",
				"Objective Met": "",
				"Scored Value (Calculated)": "",
				"supportingExample": "Volunteers or is requested to work on additional objectives in addition to current assignment AND continues to meet expectations for both",
				"counterExample": "Work on internal IP while on the bench. Works on additional work but routinely misses delivery dates.",
				"Notes": "",
				"Number": 61
			}
		]
	};
	res.send(list);
});

module.exports = router;